function label_format_examples(~, ~)
    
text_width = 320;
text_height = 110;
inset = 15;

set(0,'units','pixels')
res = get(0,'screensize');
window_width = text_width + inset*2;
window_height = text_height + inset*2;

figure('MenuBar', 'none', 'ToolBar', 'none', 'Name', 'X-Tick Label Format Examples', 'NumberTitle', 'off',...
    'Units', 'Pixels', 'Position', [(res(3)-window_width)/2, (res(4)-window_height)/2+30, window_width, window_height]);

url = 'https://www.mathworks.com/help/matlab/ref/datetick.html#btpmlwj-1-dateFormat';
msg_str = sprintf(['<html>See <a href="' url '">documentation</a> for list, descriptions, '...
    'and examples of symbolic identifiers accepted here. For example:<br>',...
    '&emsp;yyyy-mm-dd&emsp;&emsp;&emsp;&emsp;&ensp;=>&emsp;%s<br>'...
    '&emsp;dd/mm/yyyy HH:MM&emsp;=>&emsp;%s<br>'...
    '&emsp;dd HH:MM:SS AM&emsp;&emsp;&ensp;&nbsp;=>&emsp;%s<br>'...
    '&emsp;mm/dd HH AM&emsp;&emsp;&emsp;&emsp;=>&emsp;%s</html>'],...
    datestr(now(), 'yyyy-mm-dd'),...
    datestr(now(), 'dd/mm/yyyy HH:MM'),...
    datestr(now(), 'dd HH:MM:SS AM'),...
    datestr(now(), 'mm/dd HH PM'));

jLabel = javaObjectEDT('javax.swing.JLabel', msg_str);
[hjLabel,~] = javacomponent(jLabel, [inset, window_height-inset-text_height, text_width, text_height], gcf);
hjLabel.setCursor(java.awt.Cursor.getPredefinedCursor(java.awt.Cursor.HAND_CURSOR));
set(hjLabel, 'MouseClickedCallback', @(h,e)web(url, '-browser'))